# Generated by Django 4.0.6 on 2022-08-01 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('item_name', models.CharField(max_length=100)),
                ('item_desc', models.TextField()),
                ('item_price', models.IntegerField(default=0)),
                ('item_stock', models.IntegerField(default=0)),
            ],
        ),
    ]
